--- !define

SVN_CLIENT_PATH_FOR_Win: "C:/p4client/dev_install/bin/Win/wsvn/wsvn.exe"
SVN_CLIENT_PATH_FOR_Mac: "/usr/local/bin/wsvn"
SVN_CLIENT_PATH: $(SVN_CLIENT_PATH_FOR_$(CURRENT_OS))

SET_ICON_PATH: "/usr/local/bin/setIcon"

SVN_REPO_URL: "file:///Volumes/SvnSrv/192.168.13.108/V9"

__include__: "$(SVN_REPO_URL)/instl/index.yaml"

#WAVES_DIR: "$(HOME_DIR)/Desktop/local-install"
#WAVES_PROGRAMDATA_DIR_FOR_Mac: "$(WAVES_DIR)/Application Support/Waves Audio"

#REPO_REV: 80

MAIN_INSTALL_TARGETS:
    - SG_Driver_IID
    - SG_IO_Modules_IID
    - MultiRack_SoundGrid_apps_IID
    - SG_Monitor_IID
    - WaveShell_WPAPI_V9_2_IID
    - WaveShell_WPAPI_V9_7_IID
    - EMO_IID
    - StudioRack_IID
    - SignalGenerator_IID
    - MultiRack_Plugin_Only_IID
    - WavesLib_9_1_IID
    - WavesLib_9_2_IID
