--- !define

SVN_CLIENT_PATH_FOR_Win: "C:/p4client/dev_install/bin/Win/wsvn/wsvn.exe"
SVN_CLIENT_PATH_FOR_Mac: "/usr/local/bin/wsvn"
SVN_CLIENT_PATH: $(SVN_CLIENT_PATH_FOR_$(CURRENT_OS))
SVN_REPO_URL: "http://192.168.13.108/svn/V9"

SET_ICON_PATH: "/usr/local/bin/setIcon"

INDEX_PATH_FOR_Win: "C:/p4client/dev_install/bin/Win/wsvn/wsvn.exe"
INDEX_PATH_FOR_Mac: "/Volumes/SvnSrv/192.168.13.108/V9/instl/index.yaml"
INDEX_PATH: $(INDEX_PATH_FOR_$(CURRENT_OS))

__include__: $(INDEX_PATH)

WAVES_DIR_FOR_Win: "C:/p4client/dev_install/bin/Win/wsvn/wsvn.exe"
WAVES_DIR_FOR_Mac: "/usr/local/bin/wsvn"
WAVES_DIR: $(WAVES_DIR_FOR_$(CURRENT_OS))

WAVES_DIR: "$(HOME)/Desktop/local-install"
MACOS_APPLICATIONSUPPORT_DIR: "$(WAVES_DIR)/Application Support"
MACOS_WAVESHELL_DAE_DIR: "$(WAVES_DIR)/DAE Plug-ins"
MACOS_WAVESHELL_VST_3_DIR: "$(WAVES_DIR)/VST3"
WAVESHELL_VST_2_4_DIR: "$(WAVES_DIR)/VST2"
MACOS_WAVESHELL_AU_DIR: "$(WAVES_DIR)/AU"

MAIN_INSTALL_TARGETS:
    - AudioTrack_IID
